### ISSUE TITLE
debug kit 3.2 error 

### ISSUE THREAD

**Issue by dhananjayve** [cakephp/debug_kit#473] opened 2017-01-13 10:25 UTC
i have installed cakephp using composer
composer create-project --prefer-dist cakephp/app testapp

Installation was successful. but when i have open app in browser i got this error

Fatal error: Call to undefined method Cake\Network\Response::getBody() in \testapp\vendor\cakephp\debug_kit\src\ToolbarService.php on line 213

**Comment by josegonzalez** [comment] 2017-01-13 10:50
Duplicate of #471.

**Closed by josegonzalez** 2017-01-13 10:50 UTC

**Comment by dhananjayve** [comment] 2017-01-13 10:54
Thank you
