### ISSUE TITLE
warnings in cakephp 3.4.0-beta1

### ISSUE THREAD

**Issue by luke83** [cakephp/debug_kit#469] opened 2016-12-31 11:05 UTC
**php**: 5.6.29
**cakephp**: 3.4.0-beta1 (cakephp/cakephp@d04f88ab5b7bc1576c0b153bc0f84dec7101fdfe)
**debug kit**: 3.3.5 (62edba7)

I got this warnings:

```
Warning (4096): Argument 2 passed to Cake\Controller\Controller::__construct() must be an instance of Cake\Network\Response, instance of Cake\Http\Response given [CORE/src/Controller/Controller.php, line 232]
Warning (4096): Argument 3 passed to Cake\View\ViewBuilder::build() must be an instance of Cake\Network\Response, instance of Cake\Http\Response given, called in vendor/cakephp/cakephp/src/View/ViewVarsTrait.php on line 119 and defined [CORE/src/View/ViewBuilder.php, line 600]
Warning (4096): Argument 2 passed to Cake\View\SerializedView::__construct() must be an instance of Cake\Network\Response, instance of Cake\Http\Response given, called in vendor/cakephp/cakephp/src/View/ViewBuilder.php on line 629 and defined [CORE/src/View/SerializedView.php, line 45]
Warning (4096): Argument 2 passed to Cake\View\View::__construct() must be an instance of Cake\Network\Response, instance of Cake\Http\Response given, called in vendor/cakephp/cakephp/src/View/SerializedView.php on line 49 and defined [CORE/src/View/View.php, line 319]
Warning (4096): Argument 3 passed to Cake\View\ViewBuilder::build() must be an instance of Cake\Network\Response, instance of Cake\Http\Response given, called in vendor/cakephp/cakephp/src/View/ViewVarsTrait.php on line 119 and defined [CORE/src/View/ViewBuilder.php, line 600]
Warning (4096): Argument 2 passed to Cake\View\SerializedView::__construct() must be an instance of Cake\Network\Response, instance of Cake\Http\Response given, called in vendor/cakephp/cakephp/src/View/ViewBuilder.php on line 629 and defined [CORE/src/View/SerializedView.php, line 45]
Warning (4096): Argument 2 passed to Cake\View\View::__construct() must be an instance of Cake\Network\Response, instance of Cake\Http\Response given, called in vendor/cakephp/cakephp/src/View/SerializedView.php on line 49 and defined [CORE/src/View/View.php, line 319]
Warning (4096): Argument 2 passed to DebugKit\ToolbarService::saveData() must be an instance of Cake\Network\Response, instance of Cake\Http\Response given, called in vendor/cakephp/debug_kit/src/Routing/Filter/DebugBarFilter.php on line 139 and defined [ROOT/vendor/cakephp/debug_kit/src/ToolbarService.php, line 156]
```

Detail for first warning (let me know if you need detail for all of them):
```
Cake\Controller\Controller::__construct() - CORE/src/Controller/Controller.php, line 232
ReflectionClass::newInstance() - [internal], line ??
Cake\Http\ControllerFactory::create() - CORE/src/Http/ControllerFactory.php, line 77
Cake\Http\ActionDispatcher::dispatch() - CORE/src/Http/ActionDispatcher.php, line 90
Cake\Http\BaseApplication::__invoke() - CORE/src/Http/BaseApplication.php, line 78
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\RoutingMiddleware::__invoke() - CORE/src/Routing/Middleware/RoutingMiddleware.php, line 62
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Routing\Middleware\AssetMiddleware::__invoke() - CORE/src/Routing/Middleware/AssetMiddleware.php, line 93
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Error\Middleware\ErrorHandlerMiddleware::__invoke() - CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 93
Cake\Http\Runner::__invoke() - CORE/src/Http/Runner.php, line 65
Cake\Http\Runner::run() - CORE/src/Http/Runner.php, line 51
Cake\Http\Server::run() - CORE/src/Http/Server.php, line 82
[main] - ROOT/webroot/index.php, line 37
```

**Comment by markstory** [comment] 2016-12-31 15:21
Closing as this is a dupe of cakephp/cakephp#9949

**Closed by markstory** 2016-12-31 15:21 UTC
