### ISSUE TITLE
Debug Kit causing [Violation] Avoid using document.write().

### ISSUE THREAD

**Issue by burzum** [cakephp/debug_kit#604] opened 2018-04-16 12:06 UTC
I'm getting this message in my browsers console, it's comming from Debug Kit:

```sh
26a89c23-6c5c-4ffe-ad20-4e31585067b5:7 [Violation] Avoid using document.write().
(anonymous) @ 26a89c23-6c5c-4ffe-ad20-4e31585067b5:7
```

> http://localhost:3000/debug-kit/toolbar/26a89c23-6c5c-4ffe-ad20-4e31585067b5

**Comment by markstory** [comment] 2018-04-16 15:47
Where though? I wasn't able to find it in the code.

```
:( 11:46:28 mark:debug_kit (master)
$ ack 'document.write' {src,webroot}
```

**Comment by davidyell** [comment] 2018-04-30 15:52
Could it something inside the SQLite database that contains `document.write()` ? Might be worth checking with and SQLite DB browser @burzum

**Comment by othercorey** [comment] 2020-04-14 04:32
Can't reproduce and no further information provided. Closing.

**Closed by othercorey** 2020-04-14 04:32 UTC
