### ISSUE TITLE
VariablesPanel: Passed by reference Error in PHP 8

### ISSUE THREAD

**Issue by swiffer** [cakephp/debug_kit#795] opened 2020-11-15 09:20 UTC
I'm getting a lot of these (testing with PHP8.0RC3)

Warning (2): DebugKit\Panel\VariablesPanel::DebugKit\Panel\{closure}(): Argument #1 ($item) must be passed by reference, value given [ROOT/vendor/cakephp/debug_kit/src/Panel/VariablesPanel.php, line 86]

**Comment by othercorey** [comment] 2020-11-15 09:43
Please give more information. What version are you testing with?

**Comment by swiffer** [comment] 2020-11-15 10:52
Sorry - I'm testing with CakePHP 4.2.0-beta1 and DebugKit 4.3.7 now. Is there anything else I should provide ?

**Comment by swiffer** [comment] 2020-11-15 11:07
Fixed by #796 ? Follow up of #783, reverted in 0926486bf0a42ccc1c1b178219bee1c1904fe8d2

**Comment by swiffer** [comment] 2020-11-15 12:10
The change fixes the issue in my project, but the test is failing again. I don't know why

**Comment by othercorey** [comment] 2020-11-15 22:26
We can't run php 8 tests correctly until cakephp 4.2 is released because of phpunit 9 changes.

**Comment by othercorey** [comment] 2020-11-28 14:04
I cannot reproduce this with php 8 rc5.

**Comment by othercorey** [comment] 2020-11-28 14:10
It does look like this code needs work, but I would like to start with reproducing the error.

**Comment by swiffer** [comment] 2020-11-28 15:30
I'm experiencing the error when running debug kit in browser after upgrading to php8 rc3 - still present with 8.0 final for me. it's fixed by applying #796 - however testsuite does not pass then.

**Comment by othercorey** [comment] 2020-11-28 15:45
We must be suppressing the warning in unit tests somehow.

**Comment by othercorey** [comment] 2020-11-28 16:48
I found where the error was being suppressed and can now reproduce the error with php 8.

**Comment by othercorey** [comment] 2020-12-05 05:12
This should be fixed now.

**Closed by othercorey** 2020-12-05 05:12 UTC
