### ISSUE TITLE
Missing nginx configuration when expires is set

### ISSUE THREAD

**Issue by Aerue** [cakephp/debug_kit#435] opened 2016-08-25 23:15 UTC
I have set my nginx configuration to audit my website with cache, but debug_kit not work if I send js, css and images with cache...

I have taken this example for my nginx expires configuration : https://serversforhackers.com/nginx-caching

Maybe he should be great to have this example in the doc and tell how to configure for working with debug_kit for tests purpores.

**Comment by markstory** [comment] 2016-08-25 23:59
What doesn't work when nginx is serving the assets? Do the requests 404, or are there errors in the javascript console?

**Comment by Aerue** [comment] 2016-08-26 00:13
The request does a 404

**Comment by markstory** [comment] 2016-08-26 00:25
So you'll have to figure out how to configure nginx so that the requests don't 404. :smile:

**Comment by Aerue** [comment] 2016-08-26 01:26
Yeah I gonna check more the doc tomoroww, but like the doc says infos about how configure cakePHP to nginx, i think it should be a nice feature to update the doc and talk about configuring nginx to cakephp with expires (cache). ?

**Comment by markstory** [comment] 2016-08-26 01:52
I'm not sure the CakePHP docs are the best place to be describing nginx configuration, as I don't think there would be much specific to CakePHP, unless I'm not understanding something.

**Comment by Aerue** [comment] 2016-08-26 10:54
CakePHP provide informations about nginx configuration : http://book.cakephp.org/3.0/en/installation.html#nginx

Which is quite good for me, I just send the link at my admin system to get my config, having configurations about gzip / expires should be an extras, and not quite necessary ?

**Comment by markstory** [comment] 2016-08-26 14:28
@Aerue My concern with including caching headers is that cache durations and strategies can vary quite a bit depending on the application requirements.

**Comment by smarek** [comment] 2018-07-03 12:16
Well just stumbled upon this, my usual nginx configuration includes block like this:
```nginx
        location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt)$ {
                access_log        off;
                expires           max;
        }
```

Having this block enabled when using DebugKit will result in 404 errors loading URL `domain.com/debug_kit/js/toolbar.js?1528684432`

Simply disabling the block will work, but that will cancel out the caching effort.

Solution to the problem is modifying the block with `try_files` directive like this:
```nginx
        location ~* ^.+.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt)$ {
                access_log        off;
                expires           max;
                try_files         $uri $uri/ /index.php?$args;
        }
```

**Comment by dereuromark** [comment] 2019-12-08 13:37
Any docs update we can do here, otherwise we should close this.

**Comment by smarek** [comment] 2019-12-09 17:28
@dereuromark I'd introduce section Nginx Configuration to https://book.cakephp.org/debugkit/3/en/index.html and put up the note, that DebugKit uses various resources, and all of them must be requested through index.php, possibly with correct example from my last comment https://github.com/cakephp/debug_kit/issues/435#issuecomment-402134929

**Closed** 2021-12-11 16:33 UTC
Labels: on hold
