### ISSUE TITLE
3.5.1 Fatal Error

### ISSUE THREAD

**Issue by AdrienCS** [cakephp/debug_kit#472] opened 2017-01-13 09:41 UTC
Updating debug-kit

``` Shell
  - Removing cakephp/debug_kit (3.5.0)
  - Installing cakephp/debug_kit (3.5.1)
    Downloading: 100%
```

Lead to
``` Shell
Fatal error: Call to undefined method Cake\Network\Response::getBody() in /Users/Shared/Sites/myproject/vendor/cakephp/debug_kit/src/ToolbarService.php on line 213

Fatal error: Call to undefined method Cake\Network\Response::getBody() in /Users/Shared/Sites/myproject/vendor/cakephp/debug_kit/src/ToolbarService.php on line 213
``` 

On all my CakePHP project.

**Comment by AdrienCS** [comment] 2017-01-13 09:43
Dupe #471

**Comment by josegonzalez** [comment] 2017-01-13 10:50
Duplicate of #471.

**Closed by josegonzalez** 2017-01-13 10:50 UTC
