### ISSUE TITLE
Error: Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by tsmsogn** [cakephp/debug_kit#549] opened 2017-09-13 05:47 UTC
I have error when I try to pass [serializer](https://github.com/schmittjoh/serializer) from controller to `.ctp` with `$this->set()`.

My environment:
```
PHP 5.6.30
CakePHP 2.8.3
DubugKit 2.2.4
jms/serializer 1.1.0
```

My code:
```php
$serializer = JMS\Serializer\SerializerBuilder::create()->build();
$this->set('serializer', $serializer);
```

Stack trace:
```
CORE/Cake/Cache/Engine/FileEngine.php line 130 → serialize(array)
CORE/Cake/Cache/Cache.php line 317 → FileEngine->write(string, array, integer)
APP/Plugin/DebugKit/Controller/Component/ToolbarComponent.php line 501 → Cache::write(string, array, string)
APP/Plugin/DebugKit/Controller/Component/ToolbarComponent.php line 330 → ToolbarComponent->_saveState(FileSystemsController, array)
[internal function] → ToolbarComponent->beforeRender(FileSystemsController)
CORE/Cake/Utility/ObjectCollection.php line 128 → call_user_func_array(array, array)
[internal function] → ObjectCollection->trigger(CakeEvent)
CORE/Cake/Event/CakeEventManager.php line 243 → call_user_func(array, CakeEvent)
CORE/Cake/Controller/Controller.php line 936 → CakeEventManager->dispatch(CakeEvent)
CORE/Cake/Routing/Dispatcher.php line 200 → Controller->render()
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(FileSystemsController, CakeRequest)
APP/webroot/index.php line 109 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

**Comment by tsmsogn** [comment] 2017-09-13 05:50
I think this issue is similar to #447

**Comment by lorenzo** [comment] 2017-09-13 07:27
You are using an old version of debugkit, maybe try upgrading it first?

**Comment by lorenzo** [comment] 2017-09-13 07:27
Oh, this is even with cake 2, I actually don't remember what the last version for cake 2 is

**Comment by tsmsogn** [comment] 2017-09-13 07:56
@lorenzo Thank you for your replay.

Is DebugKit 2.2.6 latest version for Cake 2 right?
I upgraded DebugKit to it, but I have same error yet.

**Comment by lorenzo** [comment] 2017-09-13 10:22
Yes, it looks like that was the last version for cake 2. If you want to try fixing it, look in this function 

https://github.com/cakephp/debug_kit/blob/2.2/Controller/Component/ToolbarComponent.php#L464-L498

Try to see under what conditions that function cannot detect that you passed a closure.

**Comment by tsmsogn** [comment] 2017-09-13 11:55
Thanks, I'll try to fix it.

**Comment by hdogan** [comment] 2018-10-29 15:03
I've got same problem with CakePHP 3.7.0 RC1, DebugKit 3.16.5 and PHP 7.2.8

I'm using closures on validation rules (`rule` key) and conditions (`on` key), if I remove them that error message disappears.

**Comment by saeideng** [comment] 2018-10-29 16:01
@hdogan  How can someone reproduce this issue?
there is a detector for Closure here
https://github.com/cakephp/debug_kit/blob/fa82e8aa74297f7fb8d6a961479992a0dab12f05/src/Panel/VariablesPanel.php#L111-L115

**Comment by hdogan** [comment] 2018-10-29 16:09
@saeideng sorry it was on CakePHP 3.6.12. I'm going to test again with 3.7.0-RC1.

**Comment by hdogan** [comment] 2018-10-29 16:40
@saeideng I've checked DebugKit source code installed and yes there is a Closure detector in there.

I've tested with CakePHP 3.next and DebugKit 3.next.

Here is the code which causes that error (it's from `Form` object). If I remark/remove that code, the error message disappears.

```php
$validator->add('test', 'test', [
    'rule' => function ($value, $context) {
        return true;
    },
]);
```

I've debugged DebugKit source code and that validation Closure was not detected by any condition.

**Comment by hdogan** [comment] 2018-10-29 16:48
@saeideng found another part of cause:

Removing `get_object_vars()` call in __debugInfo() in `Form` fixes the error message too.

https://github.com/cakephp/cakephp/blob/03d01d5528fe93039fc757431bb1c91efcfe09ff/src/Form/Form.php#L379

**Comment by saeideng** [comment] 2018-10-29 23:08
are you using `$this->set(...)` to pass data to view ?
could you show complete code ?

**Comment by hdogan** [comment] 2018-10-30 07:52
Yes, action contains just simple form processing code.

```php
$form = new SampleForm();

if ($this->request->is('post')) {
    if ($form->execute($this->request->getData())) {
        return $this->redirect(['action' => 'index']);
    }
}

$this->set(compact('form'));
```

By the way, I've tested it with `Table` object too and it causes the same error if I use `Closure` in any validation rule.

**Comment by saeideng** [comment] 2018-11-05 20:05
@hdogan  I could not reproduce this 

my code
```php
//controller
  public function form(){
    $form = new SampleForm();
    if ($this->request->is('post')) {
        if ($form->execute($this->request->getData())) {
            return $this->redirect(['action' => 'form']);
        }
    }
    $this->set(compact('form'));
  }
/// simpleForm
class SampleForm extends Form
{

    protected function _buildValidator(Validator $validator)
    {
        $validator->add('test', 'test', [
            'rule' => function ($value, $context) {
                return true;
            },
            'on' => function ($context) {
                return true;
            }
        ]);

        return $validator;
    }

    protected function _execute(array $data)
    {
        return true;
    }
}
//form.ctp
echo $this->Form->create($form);
echo $this->Form->control('test');
echo $this->Form->button('Submit');
echo $this->Form->end();
```

tested on both `master` and `3.next` ( core and debug_kit )

**Comment by saeideng** [comment] 2018-11-05 20:07
debug_kit , variables tab : `Serialization of 'Closure' is not allowed`

**Comment by dereuromark** [comment] 2019-02-21 13:33
Is this solved in 2.x now somehow? Then we should close this.

**Comment by saeideng** [comment] 2019-02-21 17:27
@dereuromark  I could not reproduce the problem 
so closing for now,
feel free to open another issue with details if someone could reproduce  it

**Closed by saeideng** 2019-02-21 17:27 UTC
Labels: defect
