### ISSUE TITLE
Debug kit not showing in cakephp 4

### ISSUE THREAD

**Issue by rsuyambu** [cakephp/debug_kit#817] opened 2021-01-25 10:49 UTC
Debug kit not showing in cakephp 4, getting the following error.

GET http://localhost:8765/debug-kit/toolbar/8314192b-24f2-4a2d-b930-00ee597d5359 404 (Not Found)

Cake\Routing\Exception\MissingRouteException

Used the below steps to configure the debug kit
Option 1: 
php composer.phar require --dev cakephp/debug_kit "~4.0"
bin/cake plugin load DebugKit
set the debug value as true in app.php

Option 2: 
php composer.phar require --dev cakephp/debug_kit "~4.0"
$this->addPlugin('DebugKit', ['bootstrap' => true, 'routes' => true, 'middleware' => true]); // Tried this line in Application.php and bootstrap.php

Getting the same error

**Comment by markstory** [comment] 2021-01-26 04:36
I'm not able to reproduce the problem you're having. Does the icon show up at the bottom of the page?

**Comment by othercorey** [comment] 2021-01-26 04:43
I wonder if they have asset middleware loaded.

**Comment by FinlayDaG33k** [comment] 2021-01-26 11:14
I have had this error as well a little while ago, in `tmp/cache` delete the file named `myapp_cake_routes_route_collection` then refresh your page.

**Comment by rsuyambu** [comment] 2021-01-26 11:58
@markstory markstory
Yes, Icon is displayed, but while clicking icon no action

@FinlayDaG33k 
deleted models and persistent catch, but still I have the same error

**Comment by markstory** [comment] 2021-01-26 15:18
You can also check that the sqlite database (or other database if you've configured it) has records in it.

**Comment by rsuyambu** [comment] 2021-01-27 04:13
> You can also check that the sqlite database (or other database if you've configured it) has records in it.

I am using mysql database, I dont see any issue with storing or retriving the data in database tables.

**Comment by markstory** [comment] 2021-01-27 05:18
You don't put are you sure that debug kit can read the database? Do the debug kit routes show up in `bin/cake routes`

**Comment by rsuyambu** [comment] 2021-01-27 05:33
> You don't put are you sure that debug kit can read the database? Do the debug kit routes show up in `bin/cake routes`


Thank you, Yes, Debug kit added in the route, but getting error like "Cake\Routing\Exception\MissingRouteException" 
 debugkit.toolbar:clearcache         | /debug-kit/toolbar/clear-cache            | {"action":"clearCache","controller":"Toolbar","plugin":"DebugKit"}               |
| debugkit.requests:view              | /debug-kit/toolbar/*                      | {"action":"view","controller":"Requests","plugin":"DebugKit"}                    |
| debugkit.panels:view                | /debug-kit/panels/view/*                  | {"action":"view","controller":"Panels","plugin":"DebugKit"}                      |
| debugkit.panels:index               | /debug-kit/panels/*                       | {"action":"index","controller":"Panels","plugin":"DebugKit"}                     |
| debugkit.composer:checkdependencies | /debug-kit/composer/check-dependencies    | {"action":"checkDependencies","controller":"Composer","plugin":"DebugKit"}       |
| debugkit.mailpreview:index          | /debug-kit/mail-preview                   | {"action":"index","controller":"MailPreview","plugin":"DebugKit"}                |
| debugkit.mailpreview:email          | /debug-kit/mail-preview/preview           | {"action":"email","controller":"MailPreview","plugin":"DebugKit"}                |
| debugkit.mailpreview:email          | /debug-kit/mail-preview/preview/*         | {"action":"email","controller":"MailPreview","plugin":"DebugKit"}                |
| debugkit.mailpreview:sent           | /debug-kit/mail-preview/sent/{panel}/{id} | {"action":"sent","controller":"MailPreview","plugin":"DebugKit"}                 |
| debugkit.dashboard:index            | /debug-kit                                | {"_method":"GET","action":"index","controller":"Dashboard","plugin":"DebugKit"}  |
| debugkit.dashboard:index            | /debug-kit/dashboard                      | {"_method":"GET","action":"index","controller":"Dashboard","plugin":"DebugKit"}  |
| debugkit.dashboard:reset            | /debug-kit/dashboard/reset                | {"_method":"POST","action":"reset","controller":"Dashboard","plugin":"DebugKit"} |

**Comment by markstory** [comment] 2021-01-27 20:42
I don't know what's going on then. You have routes and data is going into the database, it should all work unless your application has other middleware or logic that is causing the not found exception.

**Comment by rsuyambu** [comment] 2021-01-28 04:16
> I don't know what's going on then. You have routes and data is going into the database, it should all work unless your application has other middleware or logic that is causing the not found exception.

I dont have any other issue when I removed the debug kit from the application

**Comment by markstory** [comment] 2022-03-31 13:46
Closing as we don't have a way to reproduce this.

**Closed by markstory** 2022-03-31 13:46 UTC
