### ISSUE TITLE
Uncaught Exception: Serialization of 'Closure' is not allowed when i trow exceptions  

### ISSUE THREAD

**Issue by makamo** [cakephp/debug_kit#458] opened 2016-10-13 17:27 UTC
I have a problem with debugkit when i use php7 but if i use php5.6 its work fine.

This is the [error](http://pastebin.com/5pj0RyGV) i have when its trow exception or fatal error.

And this is the real [error](http://pastebin.com/cX4Ys0pQ) after i disable debugkit.
`//Plugin::load('DebugKit', ['bootstrap' => true, 'routes' => true]);`

My Dev Configuration 

> Php 7.0 -> [phpinfo](http://pastebin.com/en4xm6Zs) 
> CakePhp 3.3.5
> DebugKit 3.3.5

**Comment by markstory** [comment] 2016-10-13 19:04
Duplicate of #447

**Comment by markstory** [comment] 2016-10-13 19:05
How can someone reproduce this issue?

**Comment by makamo** [comment] 2016-11-21 20:27
i found the problem
when i get syntax error and i have xdebug enable 
 in DebugBarFilter.php 
around line 200 
when the try to get data about 'Variables'
its return an array about the error 
when the try to serialize ` $panel->data()['content']['error']­­­`
i get  **Uncaught Exception: Serialization of 'SplFileObject' is not allowed** 
because `$panel->data()['content']['error']­­­` is `'error' => object(ParseError) `

**Comment by makamo** [comment] 2016-11-21 22:07
I found more explication 

Its cause by the new Exception [ParseError](http://php.net/manual/en/class.parseerror.php) in php 7 
and its cause by the trace created by xdebug who return sometime an object in her "args"

**Comment by markstory** [comment] 2016-11-21 22:25
Are you including an xdebug trace in your view variables? Or is there an error page for a ParseError being rendered?

**Comment by makamo** [comment] 2016-11-22 18:11
nop its just because in php7 when the debug kit check for getting variables its eval the code in controller and when there is a syntax error or other php error. the content of variable is transform in error

**Comment by markstory** [comment] 2016-11-22 19:57
Ok, so how could I reproduce this problem? I have a few apps in php7 and don't have this issue.

**Comment by makamo** [comment] 2016-11-22 21:50
i am in Ubuntu 16 04 php7 with xdebug. 
Me and my colleague have the same configuration and the same problem

**Comment by makamo** [comment] 2016-11-22 21:54
debug_kit version 3.3.4
cakephp version 3.3.5

and this is one methode a broke for reproduce the bug 

`
public function batch($contrat_id)
    {
        $contrat = $this->ContratsHeurefacturables->Contrats->get(
            $contrat_id, [
                'contain' => ['HeuresFacturable'];
            ]
        );
        if ($this->request->is(['patch', 'post', 'put'])) {
            $contratsHeurefacturable = $this->ContratsHeurefacturables->Contrats->patchEntity($contrat, $this->request->data);
            if ($this->ContratsHeurefacturables->Contrats->save($contratsHeurefacturable)) {
                $this->Flash->success('Le taux d\'heures-hommes facturables a été sauvegardé.');
                return $this->redirect(['controller' => 'contrats', 'action' => 'view', $contrat_id]);
            } else {
                $this->Flash->error('Le taux d\'heures-hommes facturables n\'a pas pu être sauvegardé. Veuillez réessayer.');
            }
        }
        $tasks = $this->ContratsHeurefacturables->Tasks->find('list');
        $fonctions = $this->ContratsHeurefacturables->Fonctions->find('list');
        $this->set(compact('contrat', 'fonctions', 'tasks'));
    }
`

i add `;` after ` 'contain' => ['HeuresFacturable'] `to make error

**Comment by markstory** [comment] 2016-11-24 02:49
Ok so it comes from a parse error in php7. I will try reproducing based on that.

**Comment by markstory** [comment] 2016-12-04 05:06
I tried to reproduce this and wasn't able to. I tried:

* Adding a parse error into a controller file - The error page rendered without any issues.
* Creating invalid SQL inside a closure to ensure that there was one on the call stack. In this case I also got a functioning error page. The code I used was
```php
        $search = function() {
            $query = $this->Bookmarks->find()
                ->where(['invalid IN' => ['derp', 'cakephp']])
                ->toArray();
        };
        $search();
```
I also tried inserting a parse error in the above closure function, but wasn't able to reproduce what you are seeing.

Is there a way you could provide me with a controller class that when added to a new project would let me reproduce the issue?

**Closed** 2017-03-04 02:37 UTC
Labels: on hold

**Comment by markstory** [comment] 2017-09-01 15:40
@Soufraz I have no idea on how to reproduce it. So it was never 'fixed'.

**Comment by Soufraz** [comment] 2017-09-01 20:07
The error appears in Cache/Engine/FileEngine.php line 130.  `$data = serialize($data);`
In my case $data has:

```
Array
(
    [LC_MESSAGES] => Array
        (
            [Component initialization and startup] => Array
                (
                    [] => 
                )

            [Controller Action] => Array
                (
                    [] => 
                )

            [Render Controller Action] => Array
                (
                    [] => 
                )

            [Could not load DebugToolbar panel %s] => Array
                (
                    [] => 
                )

            [There are no active panels. You must enable a panel to see its output.] => Array
                (
                    [] => 
                )

            [Request History] => Array
                (
                    [] => 
                )

            [No previous requests logged.] => Array
                (
                    [] => 
                )

            [previous requests available] => Array
                (
                    [] => 
                )

            [Restore to current request] => Array
                (
                    [] => 
                )

            [Logs] => Array
                (
                    [] => 
                )

            [Time] => Array
                (
                    [] => 
                )

            [Message] => Array
                (
                    [] => 
                )

            [There were no log entries made this request] => Array
                (
                    [] => 
                )

            [Request] => Array
                (
                    [] => 
                )

            [Current Route] => Array
                (
                    [] => 
                )

            [Session] => Array
                (
                    [] => 
                )

            [Sql Logs] => Array
                (
                    [] => 
                )

            [toggle (%s) query explains for %s] => Array
                (
                    [] => 
                )

            [No slow queries!, or your database does not support EXPLAIN] => Array
                (
                    [] => 
                )

            [No active database connections] => Array
                (
                    [] => 
                )

            [Memory] => Array
                (
                    [] => 
                )

            [Current Memory Use] => Array
                (
                    [] => 
                )

            [Peak Memory Use] => Array
                (
                    [] => 
                )

            [Timers] => Array
                (
                    [] => 
                )

            [%s (ms)] => Array
                (
                    [] => 
                )

            [Total Request Time:] => Array
                (
                    [] => 
                )

            [Time in ms] => Array
                (
                    [] => 
                )

            [Graph] => Array
                (
                    [] => 
                )

            [View Variables] => Array
                (
                    [] => 
                )

            [Starting %sms into the request, taking %sms] => Array
                (
                    [] => 
                )

            [%plural-c] => nplurals=INTEGER;plural=EXPRESSION;
        )

)

```

**Comment by markstory** [comment] 2017-09-02 01:36
Why can't a basic array be serialized?

**Comment by Soufraz** [comment] 2017-09-02 15:59
Sorry, was my bad. I am providing a specific case. I can't post right now because var_export has 107900 lines. I am searching for the specific key that thrown the error.

**Comment by Soufraz** [comment] 2017-09-02 17:00
In my case, I have in $data array (Cache/Engine/FileEngine.php line 130) 208 items with this:
```
	array (
		'callable' =>
			Closure::__set_state(array(
			)),
		'passParams' => false,
	)
```
I don't know exactly who is the parent key. My array in $data has 107900 lines (this amount of lines appears strange) and I couldn't identify with precision the resolution of my question.

For now I added a try catch in DebugKit and at least I can see the debug bar working perfectly.
app/Plugin/DebugKit/Controller/Component/ToolbarComponent.php last line, I changed this:

`Cache::write($this->cacheKey, $history, 'debug_kit');`
for this:
```
        try {
            Cache::write($this->cacheKey, $history, 'debug_kit');
        } catch (Exception $e) {
            echo 'DebugKit Exception: ',  $e->getMessage(), "\n";
        }
```

Probably isn't a solution because the DebugKit works easily in a project from scratch with cakephp. Probably we guys with error added a bunch of things and then the error appears. But for now this exception allow me keep working and using DebugKit in development.

**Comment by vanquang9387** [comment] 2018-09-07 07:49
I also face this problem and see this part of `var_export` similar to @Soufraz's
```
           '_eventManager' => 
          CakeEventManager::__set_state(array(
             '_listeners' => 
            array (
              'Controller.initialize' => 
              array (
                0 => 
                array (
                  0 => 
                  array (
                    'callable' => 
                    Closure::__set_state(array(
                    )),
                    'passParams' => false,
                  ),
                ),
```
